
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234!

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    shwow-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 51639968784-le1205qv5gjsqrl5f080qps5bk5sekts.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile